[package]
name = "ros"
version = "0.1.0"
authors = ["lingllqs"]
edition = "2018"

[dependencies]
bootloader = "0.9.23"
volatile = "0.2.6"

[profile.dev]
panic = "abort" # panic 时禁用栈展开

[profile.release]
panic = "abort"
